/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "/home/sara/STM32CubeIDE/workspace_1.8.0/stm32f4xx_drivers/stm32f407xx_drivers/drivers/Inc/stm32f407xx.h"
#include "/home/sara/STM32CubeIDE/workspace_1.8.0/stm32f4xx_drivers/stm32f407xx_drivers/drivers/Inc/stm32f407xx_gpio_driver.h"
#include "/home/sara/STM32CubeIDE/workspace_1.8.0/stm32f4xx_drivers/stm32f407xx_drivers/drivers/Src/stm32f407xx_gpio_driver.c"

void delay(void)
{
	for(int32_t i=0; i<500000; i++);
}

int main(void)
{
	GPIO_Handle_t GpioLed;

	GpioLed.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_12;
	GpioLed.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
	GpioLed.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
	GpioLed.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
	GpioLed.GPIO_PinConfig.GPIO_PinPuPdControl = GPIO_NO_PUPD;
	GpioLed.pGPIOx = GPIOD;


	GPIO_PeriClockControl(GPIOD, ENABLE);

	//GPIO_Init(&GpioLed);

	while(1)
	{
		GPIO_ToggleOutputPin(GPIOD, GPIO_PIN_NO_12);
		delay();
	}

    /* Loop forever */
	return 0;
}
